# Generated by Django 2.2.7 on 2019-12-11 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dublincoreagent',
            options={'verbose_name': 'Dublin Core Agent', 'verbose_name_plural': 'Dublin Core Agents'},
        ),
        migrations.AlterModelOptions(
            name='dublincoreresource',
            options={'verbose_name': 'Dublin Core Resource', 'verbose_name_plural': 'Dublin Core Resources'},
        ),
        migrations.AlterModelOptions(
            name='dublincorerights',
            options={'verbose_name': 'Dublin Core Rights', 'verbose_name_plural': 'Dublin Core Rights'},
        ),
    ]
