# Generated by Django 2.1.7 on 2019-12-01 01:00

from django.db import migrations, models
import dublincore_resource.models


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublincoreresource',
            name='attachment',
            field=models.FileField(blank=True, default='', upload_to=dublincore_resource.models.get_upload_path),
        ),
    ]
