# Generated by Django 2.1.7 on 2019-12-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0002_dublincoreresource_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinCoreAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('identifier', models.URLField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='dublincoreresource',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='contributor',
            field=models.ManyToManyField(related_name='contributed_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='creator',
            field=models.ManyToManyField(related_name='created_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
    ]
