# Generated by Django 2.2.7 on 2019-12-11 14:49

import controlled_vocabulary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_remove_controlledvocabulary_test'),
        ('dublincore_resource', '0002_auto_20191211_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dublincoreresource',
            name='language',
        ),
        migrations.RemoveField(
            model_name='dublincoreresource',
            name='subject',
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='coverage',
            field=models.CharField(blank=True, default='', help_text='The spatial or temporal topic of the resource.', max_length=200),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='is_part_of',
            field=models.CharField(blank=True, default='', help_text='A related resource in which the described resource is physically or logically included.', max_length=200),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='issued',
            field=models.CharField(blank=True, default='', help_text='Date of formal issuance (e.g., publication) of the resource.', max_length=30),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='languages',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='The primary language of the resource.', null=True, related_name='_dublincoreresource_languages_+', to='controlled_vocabulary.ControlledTerm', vocabularies='iso639-2'),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='source',
            field=models.CharField(blank=True, default='', help_text='A related resource from which the described resource is derived.', max_length=200),
        ),
        migrations.AddField(
            model_name='dublincoreresource',
            name='subjects',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='The topic of the resource.', null=True, related_name='_dublincoreresource_subjects_+', to='controlled_vocabulary.ControlledTerm', vocabularies='fast-topic'),
        ),
    ]
