# Generated by Django 2.2.7 on 2019-12-11 19:17

import controlled_vocabulary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0003_auto_20191211_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincoreresource',
            name='languages',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='The primary language of the resource.', related_name='_dublincoreresource_languages_+', to='controlled_vocabulary.ControlledTerm', vocabularies='iso639-2'),
        ),
        migrations.AlterField(
            model_name='dublincoreresource',
            name='subjects',
            field=controlled_vocabulary.models.ControlledTermsField(blank=True, help_text='The topic of the resource.', related_name='_dublincoreresource_subjects_+', to='controlled_vocabulary.ControlledTerm', vocabularies='fast-topic'),
        ),
    ]
