# Generated by Django 2.1.7 on 2019-12-01 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0003_auto_20191201_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincoreresource',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='contributed_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
        migrations.AlterField(
            model_name='dublincoreresource',
            name='creator',
            field=models.ManyToManyField(blank=True, related_name='created_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
        migrations.AlterField(
            model_name='dublincoreresource',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_resources', to='dublincore_resource.DublinCoreAgent'),
        ),
    ]
