# Generated by Django 2.1.7 on 2019-12-01 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0004_auto_20191201_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dublincoreresource',
            old_name='contributor',
            new_name='contributors',
        ),
        migrations.RenameField(
            model_name='dublincoreresource',
            old_name='creator',
            new_name='creators',
        ),
    ]
