# Generated by Django 2.1.7 on 2019-12-01 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0002_auto_20191201_0009'),
        ('dublincore_resource', '0005_auto_20191201_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublincoreresource',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_resources', to='controlled_vocabulary.ControlledTerm'),
        ),
    ]
