# Generated by Django 2.2.7 on 2019-12-03 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0004_controlledvocabulary_concept'),
        ('dublincore_resource', '0006_dublincoreresource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dublincoreresource',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_resources', to='controlled_vocabulary.ControlledTerm'),
        ),
    ]
