# Generated by Django 2.2.7 on 2019-12-03 02:14

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0007_dublincoreresource_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincoreresource',
            name='language',
            field=controlled_vocabulary.models.ControlledTermField(
                'iso639-2', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_resources', to='controlled_vocabulary.ControlledTerm'),
        ),
    ]
