# Generated by Django 2.2.7 on 2019-12-03 02:54

import controlled_vocabulary.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dublincore_resource', '0008_auto_20191203_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincoreresource',
            name='type',
            field=controlled_vocabulary.models.ControlledTermField(
                'dcmitype', blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='typed_resources', to='controlled_vocabulary.ControlledTerm'),
        ),
    ]
